Optimizing pre-commit hook.

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -11,12 +11,17 @@ fi;
 echo "Running Ktlint over these files:"
 echo "$CHANGED_FILES"
 
-# Clean is required because of https://github.com/ankidroid/Anki-Android/issues/9521
-./gradlew clean
+
 # -q removes noise from the output if it fails.
 # TODO: -w is better, but https://github.com/JLLeitschuh/ktlint-gradle/issues/457 adds noise
 # -w should display: "CriticalExceptionTest.kt:19:1 Wildcard import (cannot be auto-corrected)"
-./gradlew -q ktlintFormat
+# Cleaning and retrying only if the ktlint fails
+if ! ./gradlew -q ktlintFormat ; then
+    echo "Cleaning the project and retrying."
+    # Clean is required because of https://github.com/ankidroid/Anki-Android/issues/9521
+    ./gradlew clean
+    ./gradlew -q ktlintFormat
+fi;
 
 echo "Completed ./gradlew ktlintFormat run."
 echo "$CHANGED_FILES" | while read -r file; do
